modLoader="javafml"
loaderVersion="*"
license="${license}"
issueTrackerURL="${issues}"
[[mods]]
modId="defaultoptions"
version="${version}"
displayName="${mod_name}"
displayURL="${homepage}"
logoFile="defaultoptions.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''${description}'''
[[dependencies.defaultoptions]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.defaultoptions]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.defaultoptions]]
modId="balm"
mandatory=true
versionRange="[${balm_version},)"
ordering="NONE"
side="BOTH"
