@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.blay09.mods.defaultoptions;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;