modLoader="javafml"
loaderVersion="[1,)"
license="${license}"
issueTrackerURL="${issues}"
[[mods]]
modId="defaultoptions"
version="${version}"
displayName="${mod_name}"
displayURL="${homepage}"
displayTest="NONE"
logoFile="defaultoptions.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''${description}'''
[[mixins]]
config = "defaultoptions.mixins.json"
[[mixins]]
config = "defaultoptions.neoforge.mixins.json"
[[dependencies.defaultoptions]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.defaultoptions]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.defaultoptions]]
modId="balm"
type="required"
versionRange="[${balm_version},)"
ordering="NONE"
side="BOTH"
